== Execution

=== Introduction

The `Execution` module provides mechanisms for discrete simulation (and its animation) of composite systems.
In order to understand what that means, let's look at an example.

Consider the model of a system that consists of four components A, B, C and D. These components are active
in a way that they have a particular behaviour whose execution is triggered by an input. The execution of
this behaviour takes a particular time. When they have completed their execution, they may have produced
an output, which is forwarded to another component, which in turn triggered the execution behaviour of that other
component, and so on and forth. Such systems occur often in technical applications, for example as digital
electronic circuits or production chains within factories.

TODO More description.

image::../../graffle-img/execution-model.svg[width=500]

=== High-level Requirements

TODO

=== Core Abstractions

image::../../model-img/svg/jabbah__execution__Execution Core Abstractions_20.svg[]

=== Interaction
image::../../model-img/svg/jabbah__execution__Collaboration1__Interaction1__Execution_19.svg[width=800]
