== Modul "Execution"

=== Einführung

Das Modul `Execution` stellt Mechanismen für die diskrete Simulation (und deren Animation) von zusammengestetzten Systemen
zur Verfügung. Um zu verstehen, was das bedeutet, betrachten wir ein Beispiel.

Ein System besteht aus den vier Komponenten A, B, C und D. Die Komponenten haben jeweils einen Eingang und einen
Ausgang. Sie empfangen am Eingang ein Signal, führen eine bestimmte Verarbeitung durch, und produzieren am Ausgang ein
anderes Signal, das zur nächsten Komponente weitergeleitet wird, was wiederum deren Verarbeitung des Signals anstösst.
Die Verarbarbeitung eines Signals innerhalb einer Komponente nimmt eine gewisse Zeit in Anspruch.

Solche Systeme kommen oft in technischen Anwendungen vor, z.B. in Form von digitale elekronische Schaltungen oder Produktionsketten
in Fabriken.

image::../../graffle-img/execution-model.svg[width=500]

=== Anforderungen

TODO

=== Kern-Abstraktionen

image::../../model-img/svg/jabbah__execution__Execution Core Abstractions_20.svg[]

=== Interaktionen
image::../../model-img/svg/jabbah__execution__Collaboration1__Interaction1__Execution_19.svg[width=800]
