== Edit

=== Introduction

TODO

=== Module Overview
image::../../model-img/svg/jabbah__edit__Edit Package Overview_8.svg[]

* <<edit-interfaces.adoc#, *edit:*>> Contains all important interfaces, which allows to reduce module dependencies.

* <<edit-command.adoc#, *command:*>> Provides mechanisms for implementing undo/redo functionality.

* <<edit-snap.adoc#, *snap:*>> Provides mechanisms for aligning and snapping the locations of `Components` to a `Grid`,
to guidelines, or to each other.

* <<edit-style.adoc#, *style:*>> Extends the `Style` and `Theme` classes of the `draw` module for the `edit` module.

* <<edit-tool.adoc#, *tool:*>> Provides mechanisms for developing `Tools` to be used for editing `Drawings`.

* <<edit-highlight.adoc#, *highlight:*>> Support for highlighting `Components`, which can be useful when explaining `Drawings`
to the user. In contrast to the concept of "selection", which is directly controlled by the user, highlighting is
controlled by mechanisms beyond the control of the user.

* <<edit-view.adoc#, *view:*>> Extends the `View` of the `draw` module with `Drawing`- and editing-related concepts.

* <<edit-select.adoc#, *select:*>> Support for selecting `Components` while editing them. Provides various types of
`SelectionDrawingStrategies` and `SelectionModels`, for example those that use `Handles` that allow the user to
shape a `Component`.

* <<edit-property.adoc#, *property:*>> Support for interactive editing of a `Component`'s properties using property sheets
and specialized property editors.

* <<edit-editor.adoc#, *editor:*>> Provides the basic support for editing `Drawings`.

* <<edit-model.adoc#, *model:*>> Contains various mulit-purpose `Component` implementations, such as `PolylineComponent`,
`RectangularComponent` or `TextComponent`.


=== Core Abstractions

image::../../model-img/svg/jabbah__edit__Edit Core Abstractions_7.svg[]

TODO Explain