org.gradle.jvmargs=-Xmx2048m -Duser.language=en

version_project = 1.11.1
kotlinVersion=1.9.0
kotlinWrappersVersion=1.0.0-pre.620
ktorVersion=2.3.7
kotlinCoroutinesVersion=1.8.0-RC2
mockkVersion=1.10.0
slf4jVersion=2.0.9
flatLafVersion=3.0
commonsIoVersion=2.6
commonsLang3Version=3.0
commonsBeansVersion=1.9.4
commonsCodecVersion=1.15
commonsMathVersion=3.6.1
l2fprodVersion=7.5
korteVersion=4.0.2
batikVersion=1.17

macOS_jpackage_home=/Library/Java/JavaVirtualMachines/temurin-16.jdk/Contents/Home
win_jpackage_home=C:\\Program Files\\Eclipse Foundation\\jdk-16.0.2.7-hotspot

kotlin.js.webpack.major.version=4