org.gradle.jvmargs=-Xmx2048m -Duser.language=en

version_project = 2.0.0
kotlinVersion=2.3.20
kotlinWrappersVersion=1.0.0-pre.757
ktorVersion=2.3.11
kotlinCoroutinesVersion=1.9.0-RC
slf4jVersion=2.0.9
flatLafVersion=3.5
commonsIoVersion=2.6
commonsLang3Version=3.0
commonsBeansVersion=1.9.4
commonsCodecVersion=1.15
commonsMathVersion=3.6.1
l2fprodVersion=7.7
korteVersion=4.0.2
batikVersion=1.17
jsvgVersion=1.4.0

macOS_jpackage_home=/Library/Java/JavaVirtualMachines/temurin-25.jdk/Contents/Home
win_jpackage_home=C:\\Program Files\\Eclipse Foundation\\jdk-16.0.2.7-hotspot

kotlin.js.webpack.major.version=4
