version_project = 0.13.0
kotlinVersion=1.5.10
mockkVersion=1.10.0
slf4jVersion=1.7.21
commonsIoVersion=2.6
commonsLang3Version=3.0
commonsBeansVersion=1.9.4
l2fprodVersion=7.3
macOS_jpackage_home=/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home
win_jpackage_home=C:\\Program Files\\AdoptOpenJDK\\jdk-14.0.0.36-hotspot