rootProject.name = "jabbah"

include("base")
include("base-test-util")
include("io")
include("animation")
include("draw")
include("draw-test-util")
include("edit")
include("edit-test-util")
include("execution")
include("execution-test-util")
include("app")
include("app-test-util")
include("graph")
include("antares")