package ch.scorpion.jabbah.base.dsl

import ch.scorpion.jabbah.base.parser.TokenType

enum class DslTokenType(override val id: String): TokenType {
	LITERAL("literal"),
	PLUS("+"),
	MINUS("-"),
	MULTIPLY("*"),
	DIVIDE("/"),
	CARET("^"),
	LPAREN("("),
	RPAREN(")"),
	EOF("EOF"),
	ASSIGN("="),
	ID("ID"),
	LCURLEY("{"),
	RCURLEY("}"),
	VAR("var"),
	STORE("store"),
	EQUAL("=="),
	DIFF("!="),
	SMALLER("<"),
	SMALLER_EQUAL("<="),
	GREATER(">"),
	GREATER_EQUAL(">="),
	IF("if"),
	ELSE("else"),
	AND("and"),
	OR("or"),
	NOT("not"),
	SHIFT_LEFT("<<"),
	SHIFT_RIGHT(">>"),
	MOD("%"),
	WHEN("when"),
	COLON(":"),
	FOR("for"),
	IN("in"),
	TO("to"),
	LEFT_BRACKET("["),
	RIGHT_BRACKET("]"),
	QUESTION_MARK("?"),
	RETURN("return"),

	// TokenTypes needed by higher level modules
	INIT("init"),
	AT("@"),
	HASH("#"),
	DOT("."),
	COMMA(","),
	DOUBLE_QUOTE("\""),
	SINGLE_QUOTE("'"),
	LOGIC_AND("∧"),
	LOGIC_OR("∨"),
	LOGIC_NOT("¬"),
	PROGRAMMING_AND("&&"),
	PROGRAMMING_OR("||"),
	PROGRAMMING_NOT("!")
}
