== Draw

=== Introduction

TODO

=== Module structure

image::../../model-img/svg/jabbah__draw__Draw Package Overview_1.svg[]

* <<graphics.adoc#, *graphics:*>> Contains low-level graphical objects such as `Color`, `Font` or `Stroke`, and an
abstract interface of drawing methods that are implemented in the supported platforms.
* <<draw-interfaces.adoc#, *draw:*>> Contains interfaces used by all modules of `draw`.
* <<style.adoc#, *style:*>> Contains concepts that allow an application to establish coherent visual styles for its
graphical objects, and to enable the user to switch between predefined themes.
* <<drawable.adoc#, *drawable:*>> Contains abstract `Drawable` implementations as well as some reusable, common-purpose
`Drawables` such as `IconButton` or `RectangularDrawable`.
* <<container.adoc#, *container:*>> Contains `DrawableContainer` implementations.
* <<view.adoc#, *view:*>> Contains `View` implementations and classes for zooming and navigation within a `View`.
* <<polyline.adoc#, *polyline:*>>: Contains interfaces and classes for polyline `Drawable`s.

=== Core Abstractions

This sections gives an overview of the core abstractions of the `draw` module and how they collaborate to support
building and displaying 2D graphics. Check out the various sub-module descriptions for detailed information.

image::../../model-img/svg/jabbah__draw__Draw Core Abstractions_2.svg[]

<<drawable.adoc#, *Drawable:*>> `Drawables` represent the very core of a 2D drawing application built with `draw`.
A `Drawable` can draw itself using the drawing methods provided by a `DrawContext` and its `Graphics2D` drawing interface.
`Drawables` are also an important source of repainting activity; when a `Drawable` has changed, it declares itself
as "invalid", which eventually leads to repainting activities in the `Views` that contain this `Drawable`.

<<drawable.adoc#, *DrawableListener:*>> Clients of `Drawables` can register `DrawableListeners` that get called
whenever the `Drawable` needs repainting, or when its geometry has changed. `Views` use `DrawableListeners` for
their repainting processes.

<<container.adoc#, *DrawableContainer:*>> `DrawableContainers` are composites of `Drawable`s and maintain a
configurable stacking order of the `Drawables` they contain. A `DrawableContainer` is involved in repainting
of its `Drawables` as well as in dispatching input events to them.

<<container.adoc#, *DrawableContainerListener:*>> `DrawableContainerListeners` are used to get involved whenever
`Drawables` are added to or removed from a `DrawableContainer`.

<<input-event-handling.adoc#, *InputEventHandler:*>> An `InputEventHandler` consumes input events on behalf of its `Drawable`.

<<view.adoc#, *View:*>> A `View` is the gateway between `Drawables` that need to be displayed to the user, and
the `Canvas` that implements platform-specific displaying features, such as a HTML canvas in a browser or a
`JComponent` on the JVM platform. `Views` implement zooming and panning, and they are involved in input event
dispatching, incorporating view-to-model coordinate transformations.

<<view.adoc#, *Canvas:*>> A `Canvas` is the interface to a platform-specific rendering device. Separating `View`
from `Canvas` allows to provide complex `View` implementations (including coordinate transformations and in-`View`
navigation) in a platform-independent way.

== Cross-cutting Concerns

* <<composition.adoc#, *Composition:*>> TODO
* <<repainting.adoc#, *Repainting:*>> TODO
* <<input-event-handling.adoc#, *Input Event Handling:*>>: Input event handling is the process of capturing input events
in a `Canvas` and dispatching them to the `InputEventHandler` of the `Drawable` (or to other objects, such as tool of
an editor) the user aims to.