/* gradle build file of the jabbah.io module */

apply plugin: 'kotlin'

sourceSets {
	main.kotlin.srcDirs += 'shared/src/main'
	main.kotlin.srcDirs += 'jvm/src/main'
	
	test.kotlin.srcDirs += 'shared/src/test'
	test.kotlin.srcDirs += 'jvm/src/test'
}

repositories {
	flatDir {
		dirs '../lib'
	}
}

dependencies {
	compile project(path: ':base')
	compile project(path: ':base')

	compile 'org.slf4j:slf4j-api:1.7.21'
	compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
	compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
	compile "mind:exml:7.0.0"
	compile "l2fprod:l2fprod-common-all:7.3"

	testCompile "org.jetbrains.kotlin:kotlin-test:$kotlin_version"
	testCompile "org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version"
    testImplementation "io.mockk:mockk:$mockk_version"
}
