package ch.scorpion.antares.hdl.vhdl

import ch.scorpion.antares.hdl.HDLModel
import ch.scorpion.antares.model.DigitalGraph
import ch.scorpion.jabbah.base.io.CodePrinter
import ch.scorpion.jabbah.base.logger
import ch.scorpion.jabbah.graph.MetaGraphRepository

class VHDLGenerator(
	private val repository: MetaGraphRepository,
	private val printer: CodePrinter,
	private val generateComment: Boolean = false
) {
	companion object {
		private val LOG by logger(VHDLGenerator::class)
	}

	fun generate(circuit: DigitalGraph) {
		LOG.userTrail("Exporting VHDL for '${circuit.name}' (${circuit.uuid.id})")

		val model = HDLModel(circuit, repository).create()
		model.renameLabels(VHDLRenaming())

		if (generateComment) {
			printer.println("-- Generated by Antares (www.antarescircuit.io)").println()
		}

		VHDLCreator(printer).printCircuit(model.main)
	}
}