package ch.scorpion.antares.hdl.vhdl

import ch.scorpion.antares.hdl.HDLExportParams
import ch.scorpion.antares.hdl.HDLModel
import ch.scorpion.antares.model.DigitalGraph
import ch.scorpion.jabbah.base.io.CodePrinter
import ch.scorpion.jabbah.base.logger
import java.io.FileOutputStream
import java.nio.file.Path

/**
 * Generates the [HDLModel] and exports is as a VHDL circuit file
 * and a VHDL test bench file, if required by [params].
 */
class VHDLGenerator(
	private val params: HDLExportParams,
	private val generateComment: Boolean = false
) {

	companion object {
		private val LOG by logger(VHDLGenerator::class)
		private const val COMMENT = "-- Generated by Antares (www.antarescircuit.io)"
	}

	// Used by the UI
	fun generate(circuit: DigitalGraph) {
		LOG.userTrail("Exporting VHDL for '${circuit.name}' (${circuit.uuid.id})")

		val model = createModel(circuit)
		writeCircuitFile(model, params.hdlFile)
		if (params.testBenchParams != null) {
			writeTestBenchFile(model, params.testBenchParams.tbFile)
		}
	}

	// Used for testing
	fun generateHDL(hdlPrinter: CodePrinter, circuit: DigitalGraph) {
		val model = createModel(circuit)
		writeCircuit(model, hdlPrinter)
	}

	private fun createModel(circuit: DigitalGraph): HDLModel =
		HDLModel(circuit, params.renaming)
			.create()
			.apply { renameLabels() }

	private fun writeCircuit(model: HDLModel, printer: CodePrinter) {
		printComment(printer)
		VHDLCreator(printer, applyDelays = params.useDelayModel).printCircuit(model.main)
		printer.close()
	}

	private fun writeCircuitFile(model: HDLModel, hdlFile: Path) {
		FileOutputStream(hdlFile.toFile()).use {
			CodePrinter(it).also { printer ->
				writeCircuit(model, printer)
			}
		}
	}

	private fun writeTestBench(model: HDLModel, printer: CodePrinter) {
		printComment(printer)
		VHDLTestBenchCreator(printer, model, params.baseName, params.testBenchParams!!).print()
		printer.close()
	}

	private fun writeTestBenchFile(model: HDLModel, tbFile: Path) {
		FileOutputStream(tbFile.toFile()).use {
			CodePrinter(it).also { printer ->
				writeTestBench(model, printer)
			}
		}
	}

	private fun printComment(printer: CodePrinter) {
		if (generateComment) {
			printer.println(COMMENT).println()
		}
	}
}