package ch.scorpion.antares.hdl.vhdl

import ch.scorpion.antares.hdl.HDLModel
import ch.scorpion.antares.model.DigitalGraph
import ch.scorpion.jabbah.base.io.CodePrinter
import ch.scorpion.jabbah.graph.MetaGraphRepository

class VHDLGenerator(
	private val repository: MetaGraphRepository,
	private val printer: CodePrinter,
	private val generateComment: Boolean = false
) {
	fun generate(circuit: DigitalGraph) {
		val model = HDLModel(circuit, repository).create()

		model.renameLabels(VHDLRenaming())

		if (generateComment) {
			printer.println("-- Generated by Antares (www.antarescircuit.io)").println()
		}

		VHDLCreator(printer).printCircuit(model.main)
	}
}