/* gradle build file of the ch.scorpion.jabbah.graph module */

apply plugin: 'kotlin'

sourceSets {
    main.kotlin.srcDirs += 'shared/src/main'
    main.resources.srcDirs += 'shared/rsc'
    main.kotlin.srcDirs += 'jvm/src/main'

    server.kotlin.srcDirs += 'jvm/src/server'
    server.resources.srcDirs += 'shared/rsc'

    test.kotlin.srcDirs += 'shared/src/test'
    test.resources.srcDirs += 'shared/rsc'
    test.kotlin.srcDirs += 'jvm/src/test'
}

repositories {
    flatDir {
        dirs '../lib'
    }
}

dependencies {
    compile project(':execution')
    compile project(path: ':execution', configuration:'web')

    compile project(':app')
    compile project(path: ':app', configuration:'web')

    compile 'org.slf4j:slf4j-api:1.7.21'
    compile 'org.slf4j:slf4j-log4j12:1.7.21'
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"

    serverCompile 'org.slf4j:slf4j-api:1.7.21'
    serverCompile 'org.slf4j:slf4j-log4j12:1.7.21'
    serverCompile "commons-cli:commons-cli:1.3.1"
    serverCompile "com.sparkjava:spark-core:2.5.5"
    serverCompile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    serverCompile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"

    testCompile 'junit:junit:4.12'
    testCompile 'org.hamcrest:hamcrest-core:1.3'
    testCompile 'org.hamcrest:hamcrest-library:1.3'
    testCompile "org.mockito:mockito-core:2.7.2"
    testCompile "org.jetbrains.kotlin:kotlin-test:$kotlin_version"
    testCompile "org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version"
    testCompile "com.nhaarman:mockito-kotlin:1.2.0"

    // Depending on TestTranslationsBuilder
    testCompile project(':base').sourceSets.test.output
    // Depending on StyleProviderMockBuilder
    testCompile project(':draw').sourceSets.test.output
    // Depending on TestEditorBuilder
    testCompile project(':edit').sourceSets.test.output
}

configurations {
    web
}

def jsSharedFile = file('build/libs/graph.js')

task serverJar(type: Jar) {
    from 'jvm/src/server'
    baseName = 'graph-server'
    manifest {
        attributes 'Main-Class': 'ch.scorpion.jabbah.graph.server.RestApi'
    }
}

jar.dependsOn serverJar

task jsShared(type:Exec, dependsOn: configurations.compile) {
    commandLine 'kotlinc-js', '-output', jsSharedFile, '-meta-info', '-libraries',
            '../base/build/libs/base.meta.js:' +
            '../io/build/libs/io.meta.js:' +
            '../animation/build/libs/animation.meta.js:' +
            '../draw/build/libs/draw.meta.js:' +
            '../edit/build/libs/edit.meta.js:' +
            '../app/build/libs/app.meta.js:' +
            '../execution/build/libs/execution.meta.js',
            'shared/src/main'
}

artifacts {
    web archives(jsSharedFile) {
        builtBy jsShared
    }
    archives serverJar
}

task runServer(type: JavaExec) {
    classpath = sourceSets.server.runtimeClasspath
    main = 'ch.scorpion.jabbah.graph.server.RestApi'
    args '-d', '/Users/andreas/Documents/scorpion2/jabbah/antares/library'
    //args '-d', '/Users/andreas'
}

