apply plugin: 'kotlin2js'

sourceSets {
    main.kotlin.srcDirs += 'main/kotlin'
    demo {
        kotlin {
            srcDirs += 'demo/helloAntares/kotlin'
        }
        compileClasspath += sourceSets.main.runtimeClasspath
    }
}

dependencies {
    compile project(path: ':base', configuration: 'web')
    compile files('../base/build/libs/base.meta.js')

    compile files('../base-web/build/classes/main/base-web_main.meta.js')

    compile project(path: ':io', configuration: 'web')
    compile files('../io/build/libs/io.meta.js')

    compile files('../io-web/build/classes/main/io-web_main.meta.js')

    compile project(path: ':animation', configuration: 'web')
    compile files('../animation/build/libs/animation.meta.js')

    compile project(path: ':draw', configuration: 'web')
    compile files('../draw/build/libs/draw.meta.js')

    compile files('../draw-web/build/classes/main/draw-web_main.meta.js')

    compile project(path: ':edit', configuration: 'web')
    compile files('../edit/build/libs/edit.meta.js')

    compile files('../edit-web/build/classes/main/edit-web_main.meta.js')

    compile project(path: ':app', configuration: 'web')
    compile files('../app/build/libs/app.meta.js')

    compile project(path: ':graph', configuration: 'web')
    compile files('../graph/build/libs/graph.meta.js')

    compile project(path: ':antares', configuration: 'web')
    compile files('../antares/build/libs/antares.meta.js')

    compile project(path: ':edit-web')

    compile "org.jetbrains.kotlin:kotlin-stdlib-js:$kotlin_version"
}

assemble.dependsOn demoClasses
