apply plugin: 'kotlin2js'

sourceSets {
    main.kotlin.srcDirs += 'main/kotlin'
    demo {
        kotlin {
            srcDirs += 'demo/helloAntares/kotlin'
        }
        compileClasspath += sourceSets.main.runtimeClasspath
    }
}

dependencies {
    compile project(path: ':base')
    compile files('../base/build/libs/base.meta.js')

    compile files('../base-web/build/classes/main/base-web.meta.js')

    compile project(path: ':io')
    compile files('../io/build/libs/io.meta.js')

    compile files('../io-web/build/classes/main/io-web.meta.js')

    compile project(path: ':animation')
    compile files('../animation/build/libs/animation.meta.js')

    compile project(path: ':execution')
    compile files('../execution/build/libs/execution.meta.js')

    compile project(path: ':draw')
    compile files('../draw/build/libs/draw.meta.js')

    compile files('../draw-web/build/classes/main/draw-web.meta.js')

    compile project(path: ':edit')
    compile files('../edit/build/libs/edit.meta.js')

    compile files('../edit-web/build/classes/main/edit-web.meta.js')

    compile project(path: ':app')
    compile files('../app/build/libs/app.meta.js')

    compile project(path: ':graph')
    compile files('../graph/build/libs/graph.meta.js')

    compile files('../graph-web/build/classes/main/graph-web.meta.js')

    compile project(path: ':antares')
    compile files('../antares/build/libs/antares.meta.js')

    compile project(path: ':graph-web')

    compile "org.jetbrains.kotlin:kotlin-stdlib-js:$kotlin_version"
}

assemble.dependsOn demoClasses
