/* gradle build file of the jabbah.draw module */

apply plugin: 'kotlin'

sourceSets {
	main.kotlin.srcDirs += 'shared/src/main'
	main.kotlin.srcDirs += 'jvm/src/main'
	
	test.kotlin.srcDirs += 'shared/src/test'
	test.kotlin.srcDirs += 'jvm/src/test'

	demo {
		kotlin {
			srcDirs += 'shared/src/demo'
			srcDirs += 'jvm/src/demo'
		}
		resources.srcDirs += 'jvm/rsc'
		compileClasspath += sourceSets.main.runtimeClasspath
	}
}

repositories {
	flatDir {
		dirs '../lib'
	}
}

dependencies {
	compile project(':base')
	compile project(path: ':base')
	compile project(':animation')
	compile project(path: ':animation')

	compile "org.controlsfx:controlsfx:8.40.14"
	compile 'org.slf4j:slf4j-api:1.7.21'
	compile 'org.slf4j:slf4j-log4j12:1.7.21'
	compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
	compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"

	testCompile 'junit:junit:4.12'
    testCompile 'org.hamcrest:hamcrest-core:1.3'
    testCompile 'org.hamcrest:hamcrest-library:1.3'
    testCompile "org.mockito:mockito-core:$mockito_version"
	testCompile "org.jetbrains.kotlin:kotlin-test:$kotlin_version"
	testCompile "org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version"
    testCompile "com.nhaarman.mockitokotlin2:mockito-kotlin:$mockito_kotlin_version"
}
