/* gradle build file of the jabbah.draw module */

apply plugin: 'kotlin'

sourceSets {
	main.kotlin.srcDirs += 'shared/src/main'
	main.kotlin.srcDirs += 'jvm/src/main'
	
	test.kotlin.srcDirs += 'shared/src/test'
	test.kotlin.srcDirs += 'jvm/src/test'

	demo {
		kotlin {
			srcDirs += 'shared/src/demo'
			srcDirs += 'jvm/src/demo'
		}
		resources.srcDirs += 'jvm/rsc'
		compileClasspath += sourceSets.main.runtimeClasspath
	}
}

repositories {
	flatDir {
		dirs '../lib'
	}
}

dependencies {
	compile project(':base')
	compile project(path: ':base', configuration:'web')
	compile project(':animation')
	compile project(path: ':animation', configuration:'web')

	compile "org.controlsfx:controlsfx:8.40.14"
	compile 'org.slf4j:slf4j-api:1.7.21'
	compile 'org.slf4j:slf4j-log4j12:1.7.21'
	compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
	compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"

	testCompile 'junit:junit:4.12'
    testCompile 'org.hamcrest:hamcrest-core:1.3'
    testCompile 'org.hamcrest:hamcrest-library:1.3'
    testCompile "org.mockito:mockito-core:2.7.2"
	testCompile "org.jetbrains.kotlin:kotlin-test:$kotlin_version"
	testCompile "org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version"
	testCompile "com.nhaarman:mockito-kotlin:1.2.0"
}

configurations {
	web
}

def jsSharedFile = file('build/libs/draw.js')
def jsDemoFile = file('build/libs/draw-demo.js')

task jsShared(type:Exec, dependsOn: configurations.compile) {
	commandLine 'kotlinc-js', '-output', jsSharedFile, '-meta-info', '-libraries',
			'../base/build/libs/base.meta.js:' +
			'../animation/build/libs/animation.meta.js',
			'shared/src/main'
}

task jsDemo(type:Exec, dependsOn: jsShared) {
	commandLine 'kotlinc-js', '-output', jsDemoFile, '-meta-info', '-libraries',
			'../base/build/libs/base.meta.js:' +
			'../animation/build/libs/animation.meta.js:' +
			'build/libs/draw.meta.js',
			'shared/src/demo'
}

artifacts {
	web archives(jsSharedFile) {
		builtBy jsShared
	}
}

artifacts {
	web archives(jsDemoFile) {
		builtBy jsDemo
	}
}
