/* gradle build file of the ch.scorpion.jabbah.app module */

apply plugin: 'kotlin'

sourceSets {
    main.kotlin.srcDirs += 'shared/src/main'
    main.resources.srcDirs += 'shared/rsc'
    main.kotlin.srcDirs += 'jvm/src/main'

    test.kotlin.srcDirs += 'shared/src/test'
    test.resources.srcDirs += 'shared/rsc'
    test.kotlin.srcDirs += 'jvm/src/test'

    demo {
        kotlin {
            srcDirs += "jvm/src/demo"
        }
        resources.srcDirs += 'jvm/rsc'
        compileClasspath += sourceSets.main.runtimeClasspath
    }
}

repositories {
    mavenCentral()
    flatDir {
        dirs '../lib'
    }
}

dependencies {
    compile project(':edit')
    compile project(path: ':edit', configuration:'web')

    compile 'org.slf4j:slf4j-api:1.7.21'
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    compile "commons-cli:commons-cli:1.3.1"

    testCompile 'junit:junit:4.12'
    testCompile 'org.hamcrest:hamcrest-core:1.3'
    testCompile 'org.hamcrest:hamcrest-library:1.3'
    testCompile "org.mockito:mockito-core:$mockito_version"
    testCompile "org.jetbrains.kotlin:kotlin-test:$kotlin_version"
    testCompile "org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version"
    testCompile "com.nhaarman.mockitokotlin2:mockito-kotlin:$mockito_kotlin_version"
}

configurations {
    web
}

def jsSharedFile = file('build/libs/app.js')

task jsShared(type:Exec, dependsOn: configurations.compile) {
    commandLine 'kotlinc-js', '-output', jsSharedFile, '-meta-info', '-libraries',
            '../base/build/libs/base.meta.js:' +
            '../io/build/libs/io.meta.js:' +
            '../animation/build/libs/animation.meta.js:' +
            '../draw/build/libs/draw.meta.js:' +
            '../edit/build/libs/edit.meta.js',
            'shared/src/main'
}

artifacts {
    web archives(jsSharedFile) {
        builtBy jsShared
    }
}
