== Begriffe

Dieses Dokument definiert im Sinne einer "Ubiquitous Language (DDD)" alle wichtigen, nicht trivialen Begriffe, und nennt den entsprechenden Begriff in deutscher Sprache

Die erste Version dieser Begriffsliste konzentriert sich auf Begriffe, die in der Benutzerschnittstelle und der Benutzerdokumentation vorkommen. Wenn immer möglich sollen im Programmcode dieselben Begriffe verwendet werden, obwohl es vorkommen kann, dass im Programmcode Unterschiede gemacht werden, die für die Benutzerschnittstelle nicht relevant sind.

Die Liste ist alphabetisch aufsteigend nach dem englischen Begriff sortiert.

=== Liste

Antares (Antares):: Lernplatform für digitale Schaltungen.
Author (Autor):: Der Benutzer, dem ein Projekt oder eine Bibliothek gehört und der sie als einziger bearbeiten kann.
Bit Width (Anzahl Bits):: Die Anzahl von Bits, die an einem Anschluss oder in einem Leitungsbündel gleichzeitig übertragen werden können. Kann auch als "Anzahl Bits" bezeichnet werden.
Bidirectional (Bidirektional):: Signalrichtung an einem Anschluss, der gleichzeitig Eingang und Ausgang ist.
Bundle (Bündel):: Ein exportiertes Projekt, das auch die referenzierte Bibliothek enthält.
Circuit (Schaltung):: Die darstellbare Form einer digitalen Schaltung in `antares`.
Component (Komponente):: Bestandteil einer Schaltung. Eine Komponente ist entweder elementar oder eine Teilschaltung.
Connection (Verbindung):: Im Allgemeinen die Verbindung zwischen Anschlüssen von Komponenten. In Antares wird "Wire (Leitung)" verwendet.
Control (Steuerelemente):: Komponenten einer Teilschaltung, die in das Symbol der Teilschaltung aufgenommen werden. Steuerelemente können interaktiv sein.
Description Popup (Beschreibungs-Popup):: Wird über einer Komponente angezeigt, nachdem sich die Maus eine gewisse Zeit über der Komponente befunden hat. Enthält den Namen der Komponente sowie eine Beschreibung. Die Beschreibung ist entweder die Standardbeschreibung (durch den Typ der Komponente vorgegeben) oder eine Spezial-Beschreibung, die der Autor für diese Komponenten-Instanz erfasst hat und die den Zweck dieser Komponente in der Schaltung erläutern kann.
Desktop (Werkbank):: Enthält das geöffnete Projekt und die referenzierte Bibliothek.
Developer Mode (Entwicklermodus):: `Antares` kann im Entwicklermodus gestartet werden, um Zugriff auf bestimmte Funktionen zu erhalten, die vor allem der Fehlersuche dienen.
Elementary Component (Elementare Komponente):: Eine Komponente, die keine innere Schaltung enthält.
Emmerge (Auftauchen):: Nach Eintauchen in eine Teilschaltung in derselben Ansicht wieder zu äusseren Schaltungen zurückkehren.
Error (Error):: Digitaler Signalwert, der einen Fehlerzustand anzeigt.
Explorer (Explorer):: Die Seitenleiste, die das geöffnete Projekt und die verwendete Bibliothek sowie Voransicht und Eigenschaftenansicht enthält
Folder (Verzeichnis):: Eine rekursive Gliederungsstruktur in Projekten und Bibliotheken.
Graph (Graph):: Generischer Begriff in `graph` für speicherbare Objekte. Statt diesem Begriff sollte im UI von Applikation der ensprechende konkrete Begriff verwendet werden, also z.B. "Circuit" in `antares`.
Input (Eingang):: Typ von Anschluss, der Daten entgegennehmen kann.
Immerge (Eintauchen):: Innerhalb derselben View in eine Teilschaltung eintauchen. Die Tiefe wird in der Navigationsleiste angezeigt.
Issues (Probleme):: Der Name einer Ansicht, in der Probleme angezeigt werden.
Junction (Abzweigung):: Ein Punkt, an dem sich eine Leitung in zwei weiterführende Leitungen aufteilt
Library (Bibliothek):: Enthält Schaltungen, die in Projekten referenziert werden können. Bibliotheken sind entweder vordefiniert oder benutzerdefiniert. Bibliotheken können nur durch ihren Autor verändert werden. Ein Projekt kann nur Schaltungen aus einer einzigen Bibiothek referenzieren.
Label (Beschriftung):: Der Text, der in oder neben einer Komponente angezeigt wird.
Log (Log):: Der Name einer Ansicht, in der Log-Meldungen angezeigt werden.
Main View (Hauptansicht):: Die View, welche die Schaltung enthält, die bearbeitet und für welche die Simulation gestartet werden kann. Deren Name wird in der Titelzeile des Fensters angezeigt
Navigation Bar (Navigationsleiste):: Bestandteil einer Ansicht, die das Navigieren im Teilschaltungs-Baum ermöglicht.
Output (Ausgang):: Typ von Anschluss, der Daten ausgeben kann.
Pin (Anschluss):: Nur bei Antares: Ein Anschluss, der im Symbol der Schaltung angezeigt wird.
Port (Anschluss):: Ein Anschluss ist entweder ein Eingang, ein Ausgang, oder beides gleichzeitig. Er wird in Teilschaltungen verwendet, um Signale von der umgebenden Schaltung zu übernehmen (Eingang) oder an sie weiterzugeben (Ausgang). Bestandteil einer Schaltung. Wenn das äussere Symbol gemeint ist, wird "Pin" verwendet.
Preferences (Einstellungen):: TODO.
Preview (Vorschau):: Zeigt den Namen, das Symbol und eine kurze Beschreibung der im Explorer ausgewählten Schaltung an.
Propagation Delay (Schaltverzögerung):: Die Laufzeit von Signalen von einem Eingang zu einem Ausgang einer Basiskomponente oder Teilschaltung.
Properties (Eigenschaften):: Zeigt die Eigenschaften der in der Hauptansicht ausgewählten Komponente an. Gewisse Eigenschaften können durch den Benutzer verändert werden, andere sind nicht veränderbar.
Project (Projekt):: Eine durch den Benutzer erstellte Menge von zusammengehörenden Schaltungen.
Recent (Zuletzt geöffnet):: Ermöglicht es, zuletzt geöffnete Schaltungen erneut zu öffnen
Style (Stil):: Ein Stil ist ein Name für eine Menge von grafischen Eigenschaften, die einer Komponente gegeben werden können. Beispiel: "Figur" oder "Annotation".
Signal (Signal):: Synonym von "Wert", wobei "Signal" den Schwerpunkt eher auf der Dynamik hat: Signale sind Werte, die unterwegs sind. Es kann auch der Begriff "Signal value (Signalwert)" verwendet werden, wenn der Schwerpunkt nicht bekannt ist.
Subcircuit (Teilschaltung):: Eine Komponente, die eine innere Schaltung enthält und damit rekursive Schaltungsstrukturen ermöglicht.
Subview (Unteransicht):: Eine Ansicht, welche eine geöffnete Teilschaltung anzeigt. Kann nicht bearbeitet werden. Während der Simulation können Werte von Eingängen nicht verändert werden.
Symbol (Symbol):: Die Aussenansicht einer Teilschaltung, die bei der Verwendung der Teilschaltung in einer übergeordneten Schaltung verwendet wird.
Symbol Editor (Symboleditor):: Der Editor, mit der das Symbol einer Teilschaltung bearbeitet werden kann.
Theme (Thema):: Eine Menge von Stilen und anderen grafischen Eigenschaften, die das Aussehen von Graphen beeinflussen.
Toolbar (Werkzeugleiste):: Enthält Werkzeuge
User (Benutzer):: Die Person, die die Applikation gestartet hat. Im Moment wird lediglich zwischen "Entwickler" und "Jedermann" unterschieden. In Zukunft wird es identifizierbare Benutzer und einen Anmelde-Dialog geben.
Unconnected (Unverbunden):: Ein Anschluss ist unverbunden, wenn er nicht mit einer Leitung verbunden ist. Unverbundene Anschlüsse haben immer den Wert 0.
Undefined (Undefiniert):: Digitaler Signalwert, der von einem bidirektionalen Anschluss ausgegeben werden kann und auf analoger Ebene auch als "hochohmig" bezeichnet wird.
Use Case (Anwendungsfall):: Ausprogrammierter Anwendungsfall einer Schaltung, den der Benutzer ausführen kann.
User Language (Benutzersprache):: Die Sprache, in welcher der Benutzer die Texte der Benutzerschnittstelle angezeigt wünscht.
Value (Wert):: Der Wert, der an einem Eingang anliegt oder an einem Ausgang ausgegeben wird.
View (Ansicht):: Zeigt eine einzelne Schaltung innerhalb der Workbench an und enthält eine Navigationsleiste. Begriff wird auch für andere Ansichten wie "Issues" oder "Log" verwendet.
Workbench (Arbeitsfläche):: Enthält die Ansichten von Schaltungen. Ordnet mehrere offenen Ansichten zweispaltig dar, wobei die rechte Spalte aus mehreren vertikal angeordneten Ansichten bestehen kann.
Wire (Leitung):: Eine Leitung ist eine Verbindung zwischen Komponenten, über die Signale von einer Komponente zur verbundenen Komponente fliessen können.
Wire Bundle (Leitungsbündel):: Eine Leitung, die aus mehreren schmaleren Leitungen besteht
