== Projekte und Bibliotheken

=== Übersicht

Projekte und Bibliotheken sind beides Arten, wie mehrere Schaltungen zusammengefasst und mit einem Namen versehen werden können. Intern sind sie sehr ähnlich umgesetzt, und die meisten Aktionen, die du als Benützer ausführen kannst, stehen sowohl für Projekte als auch für Bibliotheken zur Verfügung.

Der Unterschied zwischen Projekten und Bibliotheken besteht darin, dass Schaltungen aus Bibliotheken in Projekten wiederverwendet werden können, während dies bei Projekten nicht möglich ist: Projekte können nicht in anderen Projekten verwendet werden. Bibliotheken sind deshalb das, was ihr Name sagt: Eine Menge von Schaltungen, die in mehreren Projekten verwendet werden können.

=== Bibliotheken

Antares enthält standardmässig zwei Bibliotheken: Die Basis-Bibliothek und die Standard-Bibliothek. Beide Bibliotheken können durch dich als Benutzer nicht geändert werden. Du kannst ihre Schaltungen in eigenen Projekten verwenden, du kannst ihre Schaltungen öffnen, ausführen und analysieren, aber du kannst sie nicht ändern, und du kannst diesen vorgegebenen Bibliotheken keine weiteren Schaltungen hinzufügen. Dies ist so, weil deine Änderungen sonst durch einen neueren Release von Antares überschrieben werden würden.

Die **Basis-Bibliothek** enthält ausschliesslich die in Antares ausprogrammierten Basis-Komponenten wie logische Gatter, LED's, Schalter usw. In der <<../base-library/base-library.adoc#, Bibliothek-Referenz>> findest du eine Beschreibung dieser Basis-Komponenten. Du kannst die Basis-Bibliothek verwenden, um darauf basierend Projekte mit einfachen Schaltungen zu erstellen. Die Basis-Bibliothek kann auch als Grundlage verwendet werden, um eigene Bibliotheken zu erstellen.

Die **Standard-Bibliothek** enthält ebenfalls alle in Antares ausprogrammierten Basis-Komponenten. Zusätzlich beinhaltet sie wichtige, häufig verwendete Teilschaltungen wie Flip-Flops, Register und Multiplexer, die du in eigenen Projekten verwenden kannst.

Die Wahl der in der Standard-Bibliothek vorhandenen Teilschaltungen wurde weitgehend durch die Entwicklung der Beispiel-Schaltung "Mikrocomputer (Tannenbaum)" bestimmt, derjenigen Schaltung, die bei Design und Entwicklung von Antares bisher eine richtungsweisende Rolle gespielt hat. In zukünftigen Versionen von Antares werden wahrscheinlich weitere Teilschaltungen zur Standard-Biblothek hinzugefügt werden.

Das wichtigste beim Thema "Bibliotheken" aber ist, dass du selber  Bibliotheken zusammenstellen kannst, die deinen eigenen Bedürfnissen entsprechen. Dabei lernst du nicht nur viel über die Funktionsweise von Antares, sondern du kannst die Features <<../description/description.adoc#, "Beschreibungen und Erläuterungen">> einsetzen, um deine Bibliothek-Teilschaltungen zu erklären. Insbesondere wenn du ein Lehrer oder ein Autor bist, solltest du die Entwicklung deiner eigenen Bibliothek - nachdem du erste tiefere Erfahrungen mit Antares gesammelt hast - unbedingt in Betracht ziehen.

Im Kapitel <<libraries.adoc#, Bibliotheken>> erfährst du, wie du mit Bibliotheken arbeitest und eigene Bibliotheken erstellst.

=== Projekte

Projekte fassen Schaltungen zusammen, die du für ein bestimmtes Projekt benötigst und die zusammen eine Funktion erfüllen. Projekte basieren immer auf genau einer Bibliothek, die du beim Anlegen des Projekts auswählst. So basiert das Beispiel-Projekt "Mikrocomputer (Tannenbaum)" auf der Standard-Bibliothek und enthält Schaltungen wie "CPU", "Address-Dekodierer" und "ALU 16-Bit".

Im Kapitel <<projects.adoc#, Projekte>> erfährst du, wie du mit Projekten arbeitest und eigene Projekte erstellst.

=== Werkbank

Die <<workbench.adoc#, Werkbank>> ist derjenige Teil der Antares-Oberfläche, der das geöffnete Projekt sowie die verwendete Bibliothek anzeigt und dir ermöglicht, deren Schaltungen zu benützen und neue Schaltungen zu erzeugen.

=== Speicherung

Wenn Antares zum ersten Mal gestartet wird, legt es ein Arbeitsverzeichnis mit Namen "Antares" an und benützt dieses Verzeichnis, um deine Projekte und deine eigenen Bibliotheken zu speichern.

Der Ort dieses Arbeitsverzeichnisses ist abhängig vom Betriebssystem. Auf macOS befindet sich das Verzeichnis am folgenden Ort, wobei `{userName}` dein Benutzername ist:

 /Users/{userName}/Library/Application Support/Antares

Wenn du eine einzelne Schaltung bearbeitest, musst du deine Änderungen explizit speichern, d.h. du solltest regelmässig die Aktion "Speichern" ausführen. Solange solche Änderungen nicht gespeichert sind, können sie mit dem Undo-System rückgängig gemacht werden.

Änderungen an der Struktur von Projekten und Bibliotheken hingegen werden immer automatisch gespeichert. Wenn du z.B. ein Verzeichnis in einem Projekt löschst, verschwindet dieses Verzeichnis aus der Werkbank, und die neue Projektstruktur wird sofort im Arbeitsverzeichnis von Antares gesichert. Da solche Aktionen nicht rückgängig gemacht werden können, fragt dich Antares vor dem Ausführen solcher Aktionen nach einer Bestätigung.
