apply plugin: 'kotlin2js'

sourceSets {
    main.kotlin.srcDirs += 'main/kotlin'

    demo {
        kotlin {
            srcDirs += 'demo/helloedit/kotlin'
        }
        compileClasspath += sourceSets.main.runtimeClasspath
    }
}

dependencies {
    compile project(path: ':base', configuration: 'web')
    compile files('../base/build/libs/base.meta.js')

    compile files('../base-web/build/classes/main/base-web.meta.js')

    compile project(path: ':io', configuration: 'web')
    compile files('../io/build/libs/io.meta.js')

    compile project(path: ':animation', configuration: 'web')
    compile files('../animation/build/libs/animation.meta.js')

    compile project(path: ':draw', configuration: 'web')
    compile files('../draw/build/libs/draw.meta.js')

    compile files('../draw-web/build/classes/main/draw-web.meta.js')

    compile project(path: ':edit', configuration: 'web')
    compile files('../edit/build/libs/edit.meta.js')

    compile files('../edit/build/libs/edit-demo.meta.js')

    compile project(path: ':draw-web')
    compile project(path: ':io-web')

    compile "org.jetbrains.kotlin:kotlin-stdlib-js:$kotlin_version"
}

// Without this, edit-web_demo.meta.js will not be automatically built, for some reason..
assemble.dependsOn demoClasses