log4j.rootLogger=INFO, STDOUT
log4j.appender.STDOUT=org.apache.log4j.ConsoleAppender
log4j.appender.STDOUT.layout=org.apache.log4j.PatternLayout
log4j.appender.STDOUT.layout.ConversionPattern=%5p [%t] (%F:%L) - %m%n

#log4j.logger.ch.scorpion.jabbah.graph.view.app.GraphViewServiceImpl=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.view.connect.GraphViewConnectServiceImpl=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.view.net.node.NodeViewFactoryImpl=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.view.net.edge.EdgeViewFactoryImpl=DEBUG

# StateMachine
log4j.logger.ch.scorpion.jabbah.graph.view.graph.GraphViewImpl=DEBUG
log4j.logger.ch.scorpion.jabbah.base.state.StateMachine=DEBUG
log4j.logger.ch.scorpion.jabbah.draw.view.MouseEventBridge=DEBUG
log4j.logger.ch.scorpion.jabbah.draw.view.ViewImpl=DEBUG
