package io.antarescircuit.jabbah.edit.select

import io.antarescircuit.jabbah.edit.EditInputEventContext
import io.antarescircuit.jabbah.draw.View
import io.antarescircuit.jabbah.draw.InputEventHandler
import io.antarescircuit.jabbah.draw.drawable.Unzoomable
import io.antarescircuit.jabbah.draw.DrawableContainer
import io.antarescircuit.jabbah.draw.Drawable
import io.antarescircuit.jabbah.draw.graphics.Paint
import io.antarescircuit.jabbah.draw.graphics.Stroke
import io.antarescircuit.jabbah.edit.Component
import io.antarescircuit.jabbah.edit.Drawing
import io.antarescircuit.jabbah.edit.Editor
import io.antarescircuit.jabbah.base.geom.RectangularShape
import io.antarescircuit.jabbah.base.Properties


/**
 * An [RubberBand] allows the user to interactively define a graphical region in order to select [Component]s
 * in a [Drawing].
 *
 * A typical implementation of a [RubberBand] is a simple rectangle, but there are more fancy and complex
 * implementations imaginable.
 *
 * If a user starts rubberbanding, the current [Editor] delegates the input event handling to [RubberBand],
 * which in turn should update its graphical representation with every input event. After the user has completed
 * rubberbanding by releasing the mouse button, the [Editor] will iterate over all [Component]s of the
 * current [Drawing] and will ask this [RubberBand] if the particular [Component] is contained in the
 * [RubberBand]> by calling its [.contains] method.
 *
 * When rubberbanding starts with the first mouse dragged event, [RubberBand] is responsible to make its graphical
 * representation visible. It is recommended that it uses a [Drawable] and adds it to the ghost
 * [DrawableContainer] of the current [View].
 */
interface RubberBand : Unzoomable {

    companion object {

        /** The name of the border [Paint] in [Properties].  */
        const val PROP_STROKE_PAINT = "edit.select.rubberband.stroke.paint"

        /** The name of the border [Stroke] in [Properties].  */
        const val PROP_STROKE = "edit.select.rubberband.stroke"

        /** The name of the fill [Paint] in [Properties].  */
        const val PROP_FILL_PAINT = "edit.select.rubberband.fill.paint"
    }

    /**
     * Returns the [InputEventHandler] that handles the input events generated by the user in order to
     * interactively define the geometry of this [RubberBand].
     *
     * The returned [InputEventHandler] is responsible for updating the graphical representation of this
     * [RubberBand] with every input event.
     *
     * @return the [InputEventHandler] of this [RubberBand].
     */
    val inputEventHandler: InputEventHandler<EditInputEventContext>

    /**
     * Checks whether this [RubberBand] entirely contains the rectangle that is defined by the specified model
     * coordinates and sizes.
     *
     * @param x the x model coordinate of the rectangle's upper left corner
     * @param y the y model coordinate of the rectangle's upper left corner
     * @param w the width of the rectangle
     * @param h the height of the rectangle
     * @return true if this [RubberBand] entirely contains the specified rectangle
     */
    fun contains(x: Double, y: Double, w: Double, h: Double): Boolean

    fun contains(rect: RectangularShape): Boolean = contains(rect.x, rect.y, rect.width, rect.height)
}
