package ch.scorpion.antares.hdl.verilog

import ch.scorpion.antares.hdl.HDLExportParams
import ch.scorpion.antares.hdl.HDLGenerator
import ch.scorpion.antares.hdl.HDLModel
import ch.scorpion.jabbah.base.io.CodePrinter

class VerilogGenerator(
    params: HDLExportParams,
    private val generateComment: Boolean = false
) : HDLGenerator(params) {

    companion object {
        private const val COMMENT = "// Generated by Antares (www.antarescircuit.io)"
    }

    override fun writeCircuit(model: HDLModel, printer: CodePrinter) {
        val topModuleName = model.renaming.checkName(model.main.name)
        printer.use {
            printComment(it)
            VerilogCreator(it, applyDelays = params.useDelayModel).printCircuit(model.main, topModuleName)
        }
    }

    override fun writeTestBench(model: HDLModel, printer: CodePrinter) {
        printer.use {
            printComment(it)
            VerilogTestBenchCreator(it, model, params.baseName, params.testBenchParams!!).print()
        }
    }

    private fun printComment(printer: CodePrinter) {
        if (generateComment) {
            printer.println(COMMENT).println()
        }
    }
}