apply plugin: 'kotlin2js'

sourceSets {
    main.kotlin.srcDirs += 'main/kotlin'
}

dependencies {
    compile project(path: ':base', configuration: 'web')
    compile files('../base/build/libs/base.meta.js')

    compile files('../base-web/build/classes/main/base-web.meta.js')

    compile project(path: ':io', configuration: 'web')
    compile files('../io/build/libs/io.meta.js')
    
    compile project(path: ':base-web')

    compile "org.jetbrains.kotlin:kotlin-stdlib-js:$kotlin_version"
}