/* gradle build file of the ch.scorpion.jabbah.animation module */

apply plugin: 'kotlin'

sourceSets {
	main.kotlin.srcDirs += 'shared/src/main'
	
	test.kotlin.srcDirs += 'shared/src/test'
}

repositories {
	flatDir {
		dirs '../lib'
	}
}

dependencies {
	compile project(':base')
	compile project(path: ':base')

	compile 'org.slf4j:slf4j-api:1.7.21'
	compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
	compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"

	testCompile "org.jetbrains.kotlin:kotlin-test:$kotlin_version"
	testCompile "org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version"
    testImplementation "io.mockk:mockk:$mockk_version"
}
