== Script

=== Introduction

Scripts are used to specify behaviour of `GraphElements` beyond the possibilities of pure graphical and
structural modelling. An author of a `Graph` can write scripts for the following use cases:

. Recalculate the values of `OutputPorts`. Such scripts are executed by the simulator if "deep simulation" is
deactivated, and can improve the overall performance of simulated `Graphs` dramatically.
. Conditions and "On Entry" / "On Exit" actions of `Scenarios`.

It is likely that more applications of scripts will be invented in the future.

[Note]
====
*Note:* Scripts are currently written as JavaScript code fragments, which is (due to the limited DSL) conventient
event to the unexpirienced user. However, using `Graphs` containing JavaScript fragments in the web version of `Jabbah`
is a notable security risk, because such scripts are executed by `Jabbah` "as is", and nothing prevents somebody
from adding malicious code to a `GraphElement`. Is is therefore planned to replace JavaScript scripts by
a specialized DSL that is interpreted by `Jabaah` itself.
====

== Core Abstractions

image::../../../model-img/svg/jabbah__graph__script__Script Overview_13.svg[]

*ScriptGateway:* TODO

*GraphScriptGateway:* TODO

*ScriptEngine*: TODO

*GraphElemBrige*: TODO
