
log4j.rootLogger=WARN, STDOUT
log4j.appender.STDOUT=org.apache.log4j.ConsoleAppender
log4j.appender.STDOUT.layout=org.apache.log4j.PatternLayout
log4j.appender.STDOUT.layout.ConversionPattern=%5p [%t] (%F:%L) - %m%n

# Simulation
#log4j.logger.jabbah.execution.scheduler.SchedulerImpl=TRACE
#log4j.logger.antares.view.GraphViewAnimator=TRACE
#log4j.logger.antares.view.net.DigitalEdgeViewNetAnimation=TRACE

# Zooming and Panning
# log4j.logger.jabbah.draw.view.ViewImpl=DEBUG

# log4j.logger.jabbah.edit.model.text.TextComponent=DEBUG

# log4j.logger.jabbah.graph.view.scenario.ScenarioDetector=TRACE
# log4j.logger.jabbah.graph.view.scenario.ScenarioStep=TRACE

# log4j.logger.antares.model.output.LEDMatrix=TRACE
# log4j.logger.jabbah.graph.library.ContainerLibraryElement=DEBUG
# log4j.logger.jabbah.graph.library.LibraryPreviewPanel=DEBUG
# log4j.logger.jabbah.graph.view.container.ContainerDrawing=DEBUG

# log4j.logger.jabbah.animation.AnimatorImpl = INFO
# log4j.logger.antares.view.GraphViewAnimator = INFO
 log4j.logger.ch.scorpion.antares.view.net.DigitalEdgeViewNetAnimation = DEBUG

# log4j.logger.ch.scorpion.jabbah.graph.container.ContainerDrawing=DEBUG
# log4j.logger.ch.scorpion.antares.model.port.SubCircuitPort = DEBUG

log4j.logger.ch.scorpion.jabbah.execution.scheduler.SchedulerImpl=INFO

log4j.logger.ch.scorpion.jabbah.edit.view.AttentionDrawerImpl=DEBUG

log4j.logger.ch.scorpion.jabbah.graph.view.oscilloscope.OscilloscopeView=DEBUG
# log4j.logger.ch.scorpion.jabbah.draw.drawable.IconButton=DEBUG
log4j.logger.ch.scorpion.jabbah.draw.LocatableInputEventHandler=DEBUG
