
log4j.rootLogger=INFO, STDOUT
log4j.appender.STDOUT=org.apache.log4j.ConsoleAppender
log4j.appender.STDOUT.layout=org.apache.log4j.PatternLayout
log4j.appender.STDOUT.layout.ConversionPattern=%5p [%t] (%F:%L) - %m%n

# Resources
#log4j.logger.ch.scorpion.jabbah.base.TranslationsJvm=DEBUG

# Simulation
#log4j.logger.ch.scorpion.jabbah.execution.scheduler.SchedulerImpl=TRACE
#log4j.logger.ch.scorpion.antares.view.GraphViewAnimator=TRACE
#log4j.logger.ch.scorpion.antares.view.net.DigitalEdgeViewNetAnimation=TRACE
#log4j.logger.ch.scorpion.jabbah.graph.model.vertice.SubGraphVerticeRef=TRACE

# Zooming and Panning
# log4j.logger.ch.scorpion.jabbah.draw.view.ViewImpl=DEBUG
# log4j.logger.ch.scorpion.jabbah.draw.view.ZoomPanController=TRACE

# Scenario
# log4j.logger.jabbah.graph.view.scenario.ScenarioDetector=TRACE
# log4j.logger.jabbah.graph.view.scenario.ScenarioStep=TRACE

# Graph Animations
# log4j.logger.jabbah.animation.AnimatorImpl = INFO
# log4j.logger.ch.scorpion.antares.view.GraphViewAnimator = DEBUG
# log4j.logger.ch.scorpion.antares.view.net.DigitalEdgeViewNetAnimation = DEBUG

# Oscilloscope
# log4j.logger.ch.scorpion.jabbah.graph.model.oscilloscope.Oscilloscope=DEBUG
# log4j.logger.ch.scorpion.jabbah.graph.view.oscilloscope.OscilloscopeView=DEBUG
# log4j.logger.ch.scorpion.jabbah.graph.view.oscilloscope.OscilloscopeProbeView=DEBUG
# log4j.logger.ch.scorpion.jabbah.graph.view.oscilloscope.OscilloscopeProbeVerticeView=DEBUG
# log4j.logger.ch.scorpion.antares.view.oscilloscope.DigitalSignalHistoryDrawer=DEBUG
# log4j.logger.ch.scorpion.jabbah.graph.view.app.OscilloscopeViewServiceImpl=DEBUG

# Connecting
# log4j.logger.ch.scorpion.jabbah.graph.view.graph.GraphViewImpl=DEBUG
# log4j.logger.ch.scorpion.jabbah.graph.view.connect.AbstractDragEdgeViewEndpointConnector=DEBUG
# log4j.logger.ch.scorpion.jabbah.graph.view.connect.ReconnectOriginConnector=DEBUG
# log4j.logger.ch.scorpion.jabbah.graph.view.connect.DragEdgeViewEndpointHandler=DEBUG
# log4j.logger.ch.scorpion.jabbah.graph.view.connect.DragEdgeViewOriginConnector=DEBUG
# log4j.logger.ch.scorpion.jabbah.graph.view.connect.DragEdgeViewDestinationConnector=DEBUG

# Layout
# log4j.logger.ch.scorpion.jabbah.graph.view.net.edge.OrthoEdgeViewLayout=DEBUG
# log4j.logger.ch.scorpion.jabbah.graph.view.net.edge.EdgeViewImpl=DEBUG

# TooltipView
#log4j.logger.ch.scorpion.jabbah.draw.view.TooltipManager=DEBUG
#log4j.logger.ch.scorpion.jabbah.edit.select.SelectionToolImpl=DEBUG
#log4j.logger.ch.scorpion.jabbah.draw.graphics.Graphics2DJvm=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.ui.GraphViewDisplayHandler=TRACE
#log4j.logger.ch.scorpion.jabbah.graph.ui.GraphViewExecutionHandler=TRACE

# JavaFX UI
#log4j.logger.ch.scorpion.antares.AntaresFX.AntaresApplication=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.library.uifx.LibraryElementNode=DEBUG
#log4j.logger.ch.scorpion.jabbah.edit.ComponentDropHandlerFx=DEBUG

# RectangularSelectionModel
#log4j.logger.ch.scorpion.jabbah.edit.model.rectangle.RectangularReplaceSelectionModel=DEBUG

# Library, Project, Repository
#log4j.logger.ch.scorpion.jabbah.graph.library.LibraryServiceImpl=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.project.ProjectPersistencePanel=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.project.FileProjectService=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.repository.RepositoryServiceImpl=DEBUG

# Context Actions
#log4j.logger.ch.scorpion.jabbah.edit.view.ContextActionRequestHandlerJvm=DEBUG
#log4j.logger.ch.scorpion.jabbah.draw.view.FocusPanel=DEBUG
#log4j.logger.ch.scorpion.jabbah.edit.select.SelectionTool=DEBUG
