
log4j.rootLogger=INFO,STDOUT,FILE

log4j.appender.STDOUT=org.apache.log4j.ConsoleAppender
log4j.appender.STDOUT.layout=org.apache.log4j.PatternLayout
log4j.appender.STDOUT.layout.ConversionPattern=%d %5p [%t] (%F:%L) - %m%n

log4j.appender.FILE=org.apache.log4j.FileAppender
log4j.appender.FILE.File=${system.logFile}
log4j.appender.FILE.Append=false
log4j.appender.FILE.layout=org.apache.log4j.PatternLayout
log4j.appender.FILE.layout.conversionPattern=%d %5p [%t] (%F:%L) - %m%n

# Resources
#log4j.logger.ch.scorpion.jabbah.base.TranslationsJvm=DEBUG

# Application
# log4j.logger.ch.scorpion.jabbah.app.AbstractDesktopApplication=DEBUG

# Simulation
#log4j.logger.ch.scorpion.jabbah.execution.scheduler.SchedulerImpl=TRACE
#log4j.logger.ch.scorpion.antares.view.GraphViewAnimator=TRACE
#log4j.logger.ch.scorpion.antares.view.net.DigitalEdgeViewNetAnimation=TRACE
#log4j.logger.ch.scorpion.jabbah.graph.model.vertice.SubGraphVerticeRef=TRACE
#log4j.logger.ch.scorpion.jabbah.execution.scheduler.TimedSchedulerTask=TRACE

# Zooming and Panning
# log4j.logger.ch.scorpion.jabbah.draw.view.ViewImpl=DEBUG
# log4j.logger.ch.scorpion.jabbah.draw.view.ZoomPanController=TRACE

# Scenario
# log4j.logger.ch.scorpion.jabbah.graph.view.scenario.ScenarioDetector=TRACE
# log4j.logger.ch.scorpion.jabbah.graph.view.scenario.ScenarioStep=TRACE
# log4j.logger.ch.scorpion.jabbah.graph.view.graph.GraphViewImpl=DEBUG

# Graph Animations
# log4j.logger.jabbah.animation.AnimatorImpl = INFO
# log4j.logger.ch.scorpion.antares.view.GraphViewAnimator = DEBUG
# log4j.logger.ch.scorpion.antares.view.net.DigitalEdgeViewNetAnimation = DEBUG

# Oscilloscope
# log4j.logger.ch.scorpion.jabbah.graph.model.oscilloscope.Oscilloscope=DEBUG
# log4j.logger.ch.scorpion.jabbah.graph.view.oscilloscope.OscilloscopeView=DEBUG
# log4j.logger.ch.scorpion.jabbah.graph.view.oscilloscope.OscilloscopeProbeView=DEBUG
# log4j.logger.ch.scorpion.jabbah.graph.view.oscilloscope.OscilloscopeProbeVerticeView=DEBUG
# log4j.logger.ch.scorpion.antares.view.oscilloscope.DigitalSignalHistoryDrawer=DEBUG
# log4j.logger.ch.scorpion.jabbah.graph.view.app.OscilloscopeViewServiceImpl=DEBUG

# Delete/Undo Connected GraphElementViews
#log4j.logger.ch.scorpion.jabbah.graph.view.app.GraphViewServiceImpl=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.view.connect.GraphViewConnectServiceImpl=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.view.net.node.NodeViewFactoryImpl=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.view.net.edge.EdgeViewFactoryImpl=DEBUG

# Layout
# log4j.logger.ch.scorpion.jabbah.graph.view.net.edge.OrthoEdgeViewLayout=DEBUG
# log4j.logger.ch.scorpion.jabbah.graph.view.net.edge.EdgeViewImpl=DEBUG

# TooltipView
#log4j.logger.ch.scorpion.jabbah.draw.view.TooltipManager=DEBUG
#log4j.logger.ch.scorpion.jabbah.edit.select.SelectionToolImpl=DEBUG
#log4j.logger.ch.scorpion.jabbah.draw.graphics.Graphics2DJvm=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.ui.GraphViewDisplayHandler=TRACE
#log4j.logger.ch.scorpion.jabbah.graph.ui.GraphViewExecutionHandler=TRACE

# JavaFX UI
#log4j.logger.ch.scorpion.antares.AntaresFX.AntaresApplication=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.library.uifx.LibraryElementNode=DEBUG
#log4j.logger.ch.scorpion.jabbah.edit.ComponentDropHandlerFx=DEBUG

# RectangularSelectionModel
#log4j.logger.ch.scorpion.jabbah.edit.model.rectangle.RectangularReplaceSelectionModel=DEBUG

# Library, Project, Repository
#log4j.logger.ch.scorpion.jabbah.graph.library.LibraryServiceImpl=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.project.ProjectPersistencePanel=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.project.FileProjectManagementService=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.repository.RepositoryServiceImpl=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.library.FileLibraryManagementService=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.library.FileLibraryPersistenceService=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.library.LibraryHolder=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.project.ProjectHolder=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.library.LibraryTreeView=DEBUG
#log4j.logger.ch.scorpion.jabbah.base.io.ZipUtil=DEBUG

# Context Actions
#log4j.logger.ch.scorpion.jabbah.edit.view.ContextActionRequestHandlerJvm=DEBUG
#log4j.logger.ch.scorpion.jabbah.draw.view.FocusPanel=DEBUG
#log4j.logger.ch.scorpion.jabbah.edit.select.SelectionTool=DEBUG

# Dynamic Tree
#log4j.logger.ch.scorpion.jabbah.base.swing.dynamictree.DynamicTreeNode=TRACE

#log4j.logger.ch.scorpion.antares.view.input.ClockView=DEBUG
#log4j.logger.ch.scorpion.antares.view.input.KnobView=TRACE
#log4j.logger.ch.scorpion.antares.view.input.KnobModel=TRACE
#log4j.logger.ch.scorpion.jabbah.graph.ui.GraphViewExecutionHandler=TRACE

# Recursive graph structure
#log4j.logger.ch.scorpion.jabbah.graph.model.vertice.DeepVerticeLink=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.container.ContainerEditor=DEBUG

# Repainting
#log4j.logger.ch.scorpion.jabbah.draw.view.ViewImpl=DEBUG
#log4j.logger.ch.scorpion.jabbah.draw.view.InvalidatableViewPainter=DEBUG

# Invocation and Busy Handling
# log4j.logger.ch.scorpion.jabbah.base.invocation.BusyHandler=TRACE

# Property handling
#log4j.logger.ch.scorpion.jabbah.edit.AbstractPropertyPanel=DEBUG
#log4j.logger.ch.scorpion.jabbah.edit.TextPropertyEditor=DEBUG
#log4j.logger.ch.scorpion.jabbah.edit.TextPropertyRenderer=DEBUG

# Properties, Settings and Preferences
#log4j.logger.ch.scorpion.jabbah.base.preferences.PreferencesTreePanel=DEBUG

# Drag&Drop
#log4j.logger.ch.scorpion.jabbah.graph.library.LibraryTreeViewTransferHandler=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.repository.RepositoryServiceImpl=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.library.LibraryServiceImpl=DEBUG

# Tunnel
#log4j.logger.ch.scorpion.antares.model.DigitalGraph=DEBUG
#log4j.logger.ch.scorpion.antares.model.net.Tunnel=DEBUG

# Usecases
#log4j.logger.ch.scorpion.jabbah.graph.view.usecase.UsecaseRunner=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.view.usecase.UsecaseTestRunner=DEBUG
#log4j.logger.ch.scorpion.antares.script.dsl.UsecaseBridge=DEBUG
#log4j.logger.ch.scorpion.antares.script.dsl.UsecaseTestBridge=DEBUG
#log4j.logger.ch.scorpion.antares.script.dsl.AbstractDrawingViewBridge=DEBUG
#log4j.logger.ch.scorpion.jabbah.execution.scheduler=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.script.ScriptEngineJvm=DEBUG

# Explorer Search
#log4j.logger.ch.scorpion.jabbah.graph.library.LibraryTreeModelBuilder=DEBUG
#log4j.logger.ch.scorpion.jabbah.graph.library.LibraryTreePanel=DEBUG

# KeyEvent Handling
#log4j.logger.ch.scorpion.jabbah.graph.ui.GraphViewExecutionHandler=DEBUG

# Built-in Keyboard
#log4j.logger.ch.scorpion.antares.model.input.Keyboard=DEBUG
#log4j.logger.ch.scorpion.antares.model.input.Keyboard.KeyboardCalculator=DEBUG
#log4j.logger.ch.scorpion.antares.view.input.KeyboardView=DEBUG

# GraphDesktop
#log4j.logger.ch.scorpion.jabbah.graph.ui.GraphDesktopController=DEBUG
#log4j.logger.ch.scorpion.jabbah.edit.highlight.BelowSmHighlighter=DEBUG

# StateMachine
# log4j.logger.ch.scorpion.jabbah.graph.view.graph.GraphViewImpl=DEBUG
#log4j.logger.ch.scorpion.jabbah.base.state.StateMachine=DEBUG
#log4j.logger.ch.scorpion.jabbah.draw.view.MouseEventBridge=DEBUG
#log4j.logger.ch.scorpion.jabbah.draw.view.ViewImpl=DEBUG

log4j.logger.ch.scorpion.jabbah.edit.command.SourcingCommandManager=DEBUG
log4j.logger.ch.scorpion.jabbah.graph.view.net.edge.DragEdgeSegmentHandler=TRACE