/* gradle build file of the jabbah.base module */

apply plugin: 'kotlin'

sourceSets {
	main.kotlin.srcDirs += 'shared/src/main'
    main.resources.srcDirs += 'shared/rsc'
    main.kotlin.srcDirs += 'jvm/src/main'

	test.kotlin.srcDirs += 'shared/src/test'
    test.resources.srcDirs += 'shared/rsc'
    test.kotlin.srcDirs += 'jvm/src/test'
}

repositories {
	flatDir {
		dirs '../lib'
	}
}

dependencies {
	compile 'org.slf4j:slf4j-api:1.7.21'
    compile 'org.slf4j:slf4j-log4j12:1.7.21'
	compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
	compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
	compile "l2fprod:l2fprod-common-all:7.3"
	compile "org.jetbrains.kotlin:kotlin-stdlib-js:$kotlin_version"
    compile "commons-io:commons-io:2.6"
    compile "org.apache.commons:commons-lang3:3.0"

	testCompile "org.jetbrains.kotlin:kotlin-test:$kotlin_version"
	testCompile "org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version"
    testImplementation "io.mockk:mockk:$mockk_version"
}

task testJar(type: Jar) {
	from 'build/kotlin-classes/test'
	into 'libs'
	baseName = 'base-test'
}

artifacts {
	archives testJar
}
