plugins {
    id 'kotlin'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '5.2.0'
    id 'java'
}

application {
    mainClassName = 'ch.scorpion.antares.AntaresSwing'
    applicationDefaultJvmArgs = ['-Duser.language=de',  '-Xdock:name=Antares']
}

run {
    args = ['-d', '/Users/andreas/Documents/scorpion2/jabbah/antares', '-developer']
}

sourceSets {
    main.kotlin.srcDirs += 'shared/src/main'
    main.resources.srcDirs += 'shared/rsc'
    main.kotlin.srcDirs += 'jvm/src/main'

    test.kotlin.srcDirs += 'shared/src/test'
    test.resources.srcDirs += 'shared/rsc'
    test.kotlin.srcDirs += 'jvm/src/test'
}

repositories {
    flatDir {
        dirs '../lib'
    }
}

dependencies {
    compile project(':graph')
    compile project(path: ':graph')

    compile 'org.slf4j:slf4j-api:1.7.21'
    compile 'vaqua:VAqua:4.0.0'
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"

    testCompile "org.jetbrains.kotlin:kotlin-test:$kotlin_version"
    testCompile "org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version"
    testImplementation "io.mockk:mockk:$mockk_version"
}
