== Skripting in Schaltungen

=== Ausführungs-Logik

In einer <<../circuits/circuits.adoc#, Schaltung>> kann im Attribut "Funktion" ein Skript definiert werden, das bei <<../simulation.simulation.adoc#, "Flacher Simulation">> statt der Schaltung ausgeführt wird, wenn die Schaltung als Teilschaltung in einer anderen Schaltung verwendet wird.

Das Skript, das du schreibst, wird als "Function Body" der folgenden JavaScript-Funktion eingebunden:

[source,javascript]
----
function execVertice(elem) {
  // Dein Skript
}
----

Der Funktions-Parameter `elem` ist ein Objekt vom Typ <<scripting-dsl.adoc#, `CircuitElemModelBridge`>>.

==== Beispiele

===== Halbaddierer

Dieses Beispiel zeigt die Ausführungs-Logik eines 1-Bit-Halbaddierers mit 2 Eingängen "A" und "B" sowie den Ausgängen "S" (Summe) und "C" (Carry / Übertrag).

[source,javascript]
----
var a = elem.inputBit("A");
var b = elem.inputBit("B");
elem.setOutputBit("S", (a || b) && !(a && b));
elem.setOutputBit("C", a && b);
----

Beachte, wie die Signale der Eingänge ausgelesen werden, wie logische Opertionen in JavaScript ausgeführt werden, und wie die Resultate dieser Operationen als Ausgangsignale gesetzt werden.

===== Inkrementierer

Dieses Beispiel zeigt die Ausführungs-Logik eines 8-Bit-Inkrementierers mit Dateneingang "D" sowie den Ausgängen "O" (Daten) und "CO" (Carry Out / Übertrag).

[source,javascript]
----
var d = elem.input("D");
var valueIn = parseInt(d, "16");
var valueOut = (valueIn + 1) % 256;
var co = (valueIn == 255);

elem.setOutput("O", valueOut.toString("16"));
elem.setOutputBit("CO", co);
----

Da `elem.input()` eine Hex-String zurückgibt, muss dieser mit `parseInt()` zur Basis 16 in einen dezimalen Wert umgewandelt werden, damit er inkrementiert werden kann. Beim Setzen des Ausganigssignals mit `elem.setOutput()` muss der inkrementierte Wert wieder mit der JavaScript-Funktion `toString(<base:String>)` in einen hexadezimalen String umgewandelt werden.

===== 2-4 Dekodierer

Dieses Beispiel zeigt die Ausführungs-Logik eines 2-4-Dekodierers mit zwei 1-Bit-Dateneingängen "I1" und "I2", einem Enable-Eingang "EN" (Enable) sowie 4 Datenausgängen "O0" .. "O3". Der Dekodierer. Der Dekodierer wählt einen der 4 Datenausgänge anhand des 2-Bit-Wertes an den beiden Dateneingänge aus, falls "EN" gesetzt ist.

[source,javascript]
----
var en = elem.inputBit("EN");
var i0 = elem.inputBit("I0") ? 1 : 0;
var i1 = elem.inputBit("I1") ? 1 : 0;

var val = i0 + 2 * i1;

elem.setOutputBit("O0", en && val == 0);
elem.setOutputBit("O1", en && val == 1);
elem.setOutputBit("O2", en && val == 2);
elem.setOutputBit("O3", en && val == 3);
----

Beachte, wie der Wert des Enable-Einganges mittels des AND-Operators `&&` von JavaScript verwendet wird, um sicherzustellen, dass ein Ausgang nur dann auf 1 gesetzt wird, falls "EN" auch 1 ist.

=== Symbol-Darstellung

Im Symbol einer <<../subcircuits/subcircuits.adoc#, Teilschaltung>> kann Skripting verwendet werden, um die Darstellung des Symbols während der Simulation zu verändern.

TIP: Die Möglichkeiten dazu sind in der aktuellen Version von Antares noch rudimentär; zukünftige Versionen von Antares werden hier mehr Unterstützung bieten.

Das Skript, das du schreibst, wird als "Function Body" der folgenden JavaScript-Funktion eingebunden:

[source,javascript]
----
function execVerticeView(elem) {
  // Dein Skript
}
----

Der Funktions-Parameter `elem` ist ein Objekt vom Typ <<scripting-dsl.adoc#, `CircuitElemViewBridge`>>.

==== Beispiele

===== Signalfluss

Das Beispiel zeigt die Darstellungs-Logik eines Multiplexers mit zwei 4-Bit-Eingängen "A" und "B", einem 1-Bit-Auswahleingang "S" (Select) und einem 4-Bit-Datenausgang "O". Je nach Signal am Auswahleingang soll der resultierende Datenfluss vom ausgewählten Eingang zum Ausgang gezeichnet werden.

[source,javascript]
----
if (elem.inputBit("S")) {
    elem.drawDataFlow("B", "O");
} else {
     elem.drawDataFlow("A", "O");
}
----
