= Benutzerhandbuch

== Einführung

Willkommen zu Antares!

Antares ist eine Lernplatform für digitale Schaltungen. Neben Zeichnen und Simulieren von digitalen Schaltungen legt Antares einen besonderen Wert darauf, Mittel zur Verfügung zu stellen, mit deren Hilfe die Funktionsweise von Schaltungen besser verstanden werden kann.

Wenn du Antares zum ersten Mal benützt, findest du im Kapitel <<first-steps/first-steps.adoc#, "Erste Schritte">> eine einfach verständliche Einführung in Antares. Die übrigen Kapitel im Teil "Grundlagen" vertiefen wichtige Themen wie den Umgang mit Projekten und Bibliotheken.

Der Teil "Fortgeschrittene Techniken" behandelt Themen, die eher für ambitionierte Anwender wie Lehrer oder Autoren von Schulungsunterlagen von Interesse sind.

== Grundlagen

* <<first-steps/first-steps.adoc#, Erste Schritte>>
* <<projects-libraries/projects-libraries.adoc#, Projekte und Bibliotheken>>
** <<projects-libraries/libraries.adoc#, Bibliotheken>>
** <<projects-libraries/projects.adoc#, Projekte>>
** <<projects-libraries/workbench.adoc#, Werkbank>>
** <<base-library/base-library.adoc#, Bibliothek-Referenz>>
* <<circuits/circuits.adoc#, Schaltungen>>
** <<circuits/wires.adoc#, Leitungen>>
** <<subcircuits/subcircuits.adoc#, Teilschaltungen>>
* <<simulation/simulation.adoc#, Simulation>>
* <<styles/styles.adoc#, Stile und Themen>>
* <<description/description.adoc#, Beschreibungen und Erläuterungen>>

== Fortgeschrittene Techniken

* <<scripting/scripting.adoc#, Skripting>>
* <<scenarios/scenarios.adoc#, Szenarien>>
* <<usecases/usecases.adoc#, Anwendungsfälle>>
* <<oscilloscope/oscilloscope.adoc#, Oszilloskop>>